import { type Photo, type PhotographerInfo } from "@shared/schema";

export interface IStorage {
  getPhotos(): Promise<Photo[]>;
  getPhoto(id: string): Promise<Photo | undefined>;
  getPhotographerInfo(): Promise<PhotographerInfo>;
}

export class MemStorage implements IStorage {
  private photos: Photo[] = [
    {
      id: "18",
        title: "Red hibuscus",
        description: "Flowers in a busy urban center.",
        category: "Flower",
        tags: ["urban", "nature", "buildings", "flowers", "city"],
        date: "23rd September 2023",
        location: "Gurugram, India",
        camera: "Sony DSC-WX150",
        lens: "inbuilt",
        iso: "100",
        aperture: "f/3.3",
        shutterSpeed: "1/1000s",
        focalLength: "4.45mm",
        imageUrl: "https://i.ibb.co/fdQYLfPc/DSC04466-2.jpg",
        aspectRatio: "portrait",
        featured: true,
      },
    {
      id: "17",
        title: "Moon",
        description: "The moon.",
        category: "Architecture",
        tags: ["moon", "night", "dark"],
        date: "3rd June 2025",
        location: "New Delhi, India",
      camera: "Nikon D3400",
        lens: "55-300mm f/4.5 - f/5.6",
        iso: "800",
        aperture: "f/5.6",
        shutterSpeed: "1/250s",
        focalLength: "450mm (effective) 300mm (APS-C)",
        imageUrl: "https://i.ibb.co/LXTN3dwT/DSC-0801-1-1.jpg",
        aspectRatio: "square",
        featured: true,
      },
    {
      id: "16",
        title: "Look up",
        description: "As an avgeek, for me there is no better feeling than seeing a plane take off or land, being able to capture it makes me revisit how busy that cockpit must have been.",
        category: "Planes",
        tags: ["urban", "planes", "A321 Neo", "airbus", "city"],
        date: "17th May 2025",
        location: "New Delhi, India",
        camera: "Nikon D3400",
        lens: "55-300mm f/4.5 - f/5.6",
        iso: "100",
        aperture: "f/8.0",
        shutterSpeed: "1/500s",
        focalLength: "292mm (effective) 194mm (APS-C)",
        imageUrl: "https://i.ibb.co/zT52v0gq/DSC-0244-1.jpg",
        aspectRatio: "landscape",
        featured: true,
      },
    {
      id: "15",
        title: "minimalism in complexity",
        description: "This photo brings attention to the small complex geometric components that make our everyday life possible.",
        category: "Machines",
        tags: ["urban", "metro", "machines", "geometric", "city"],
        date: "14th June 2023",
        location: "New Delhi, India",
        camera: "Samsung Galaxy M21",
        lens: "48MP main",
        iso: "20",
        aperture: "f/2.0",
        shutterSpeed: "1/50s",
        focalLength: "4.6mm",
        imageUrl: "https://i.ibb.co/x9bgbmk/20230614-140052-2-1.jpg",
        aspectRatio: "portrait",
        featured: true,
      },
    {
      id: "14",
      title: "Indian Myna",
      description: "An wild Indian Myna in nature.",
      category: "Wildlife",
      tags: ["Nature", "birds", "park", "wildlife"],
      date: "6th July 2025",
      location: "New Delhi, India",
      camera: "Nikon D3400",
      lens: "55-300mm f/4.5 - f/5.6",
      iso: "100",
      aperture: "f/5.6",
      shutterSpeed: "1/10s",
      focalLength: "450mm (effective) 300mm (APS-C)",
      imageUrl: "https://i.ibb.co/Zp9YPfg6/DSC-0992-1-1.jpg",
      aspectRatio: "portrait",
      featured: true,
    },
    {
      id: "13",
      title: "Cute Monkey",
      description: "This monkey just wanted to feel included and hence gave the cutest post possible just for a shot.",
      category: "Wildlife",
      tags: ["monkey", "cute", "wildlife"],
      date: "25th May 2025",
      location: "Haridwar, India",
      camera: "Nikon D3400",
      lens: "55-300mm f/4.5 - f/5.6",
      iso: "800",
      aperture: "f/5.6",
      shutterSpeed: "1/250s",
      focalLength: "450mm (effective) 300mm (APS-C)",
      imageUrl: "https://i.ibb.co/Pvhb0qFF/DSC-0657-1-1-1.jpg",
      aspectRatio: "portrait",
      featured: true,
    },
    {
      id: "12",
      title: "Banana Monkey",
      description: "This humorous shot features a very relaxed monkey peeling off a banana.",
      category: "Wildlife",
      tags: ["nature", "monkey", "banana", "peaceful", "wildlife"],
      date: "25th May 2025",
      location: "Haridwar, India",
      camera: "Nikon D3400",
      lens: "55-300mm f/4.5 - f/5.6",
      iso: "1250",
      aperture: "f/5.3",
      shutterSpeed: "1/250s",
      focalLength: "315mm (effective) 210mm (APS-C)",
      imageUrl: "https://i.ibb.co/Jjw4d9z7/DSC-0667-1-1.jpg",
      aspectRatio: "portrait",
      featured: true,
    },
    {
      id: "11",
      title: "City Shadows",
      description: "In every corner of a city we find a monochrome crowd, blurred and anonymous moving in one direction showcasing collective emotion and timeless human connection.",
      category: "Crowd",
      tags: ["urban", "shadows", "people", "market", "city"],
      date: "25th May 2025",
      location: "Haridwar, India",
      camera: "Nikon D3400",
      lens: "18-55mm f/3.5 - f/5.6",
      iso: "450",
      aperture: "f/3.5",
      shutterSpeed: "1/250s",
      focalLength: "18mm",
      imageUrl: "https://i.ibb.co/Ng38Fwbx/DSC-0600.jpg",
      aspectRatio: "portrait",
      featured: true,
    },
    {
      id: "10",
      title: "City Patterns",
      description: "Exploring the interplay of light and patterns in urban architecture, this photograph captures the geometric beauty found in everyday city structures.",
      category: "Architecture",
      tags: ["urban", "shadows", "buildings", "geometric", "city"],
      date: "15th March 2025",
      location: "New Delhi, India",
      camera: "Samsung Galaxy S23 FE",
      lens: "50MP main",
      iso: "50",
      aperture: "f/1.8",
      shutterSpeed: "1/1250s",
      focalLength: "23mm",
      imageUrl: "https://i.ibb.co/N21P9GLp/20250318-182010.jpg",
      aspectRatio: "portrait",
      featured: true,
    },
    {
      id: "9",
      title: "Pink and White",
      description: "A pink and white cluster of very vibrant Plumeria just after light rain.",
      category: "Flowers",
      tags: ["flowers", "colors", "nature", "plants"],
      date: "16th May 2025",
      location: "Gurugram, India",
      camera: "Nikon D3400",
      lens: "55-300mm f/4.5 - f/5.6",
      iso: "6400",
      aperture: "f/5.6",
      shutterSpeed: "1/30s",
      focalLength: "450mm (effective) 300mm (APS-C)",
      imageUrl: "https://i.ibb.co/HLKNFB3z/DSC-0217-1-1.jpg",
      aspectRatio: "portrait",
      featured: true,
    },
    {
      id: "8",
      title: "Natural Grace",
      description: "A study in natural light and human emotion, capturing authentic moments that tell a deeper story.",
      category: "Hiking",
      tags: ["mountains", "natural light", "emotion", "people", "snow"],
      date: "5th January 2023",
      location: "Dalhousie, India",
      camera: "Sony DSC-WX150",
      lens: "inbuilt",
      iso: "100",
      aperture: "f/3.3",
      shutterSpeed: "1/640s",
      focalLength: "4.45mm",
      imageUrl: "https://i.ibb.co/sd6dbK0V/DSC03167-2-1.jpg",
      aspectRatio: "portrait",
      featured: false,
    },
    {
      id: "7",
      title: "Pale white dot",
      description: "Capturing the tranquil beauty of of our moon in the cloudy sky, this photo makes us ponder about our position in the universe and how small we are in comparison to the cosmic scale.",
      category: "Sky",
      tags: ["moon", "clouds", "sky", "blue", "peaceful"],
      date: "29th May 2023",
      location: "New Delhi,India",
      camera: "Sony DSC-WX150",
      lens: "inbuilt",
      iso: "100",
      aperture: "f/3.3",
      shutterSpeed: "1/320s",
      focalLength: "4.45mm",
      imageUrl: "https://i.ibb.co/4n4Lpq1W/DSC03691-2-2.jpg",
      aspectRatio: "square",
      featured: false,
    },
    {
      id: "6",
      title: "Park Stories",
      description: "Shows a dog relaxing under the sun in the cold winter weather.",
      category: "Nature",
      tags: ["dog", "nature", "trees"],
      date: "3rd January 2023",
      location: "New Delhi, India",
      camera: "Sony DSC-WX150",
      lens: "inbuilt",
      iso: "100",
      aperture: "f/5.9",
      shutterSpeed: "1/320s",
      focalLength: "44.5mm",
      imageUrl: "https://i.ibb.co/YFQs1nwN/DSC03136-2-1.jpg",
      aspectRatio: "landscape",
      featured: false,
    },
    {
      id: "5",
      title: "Grazing Mules",
      description: "This shot was taken by accident but ended up coming out really nicely, it depicts a muleteer grazing his mules on the snowy river bank.",
      category: "Nature",
      tags: ["river", "rocks", "water", "snow","mule","forest"],
      date: "10th January 2020",
      location: "Manali, India",
      camera: "Sony DSC-WX150",
      lens: "inbuilt",
      iso: "100",
      aperture: "f/5.0",
      shutterSpeed: "1/320s",
      focalLength: "16.24mm",
      imageUrl: "https://i.ibb.co/wF78yzJs/DSC02518-2.jpg",
      aspectRatio: "landscape",
      featured: false,
    },
    {
      id: "4",
      title: "Snowy Trees",
      description: "Snow covered forest showcasing the beauty of nature.",
      category: "Trees",
      tags: ["snow", "trees", "nature", "winter"],
      date: "8th January 2020",
      location: "Manali, India",
      camera: "Sony DSC-WX150",
      lens: "inbuilt",
      iso: "100",
      aperture: "f/3.3",
      shutterSpeed: "1/500s",
      focalLength: "4.45mm",
      imageUrl: "https://i.ibb.co/qYBwchZ9/DSC02384-2.jpg",
      aspectRatio: "landscape",
      featured: false,
    },
    {
      id: "3",
      title: "Snowy River",
      description: "A captivating photograph of the Beas river splashing on the rocks at the snowy river bank.",
      category: "River",
      tags: ["river", "rocks", "water", "snow"],
      date: "10th January 2020",
      location: "Manali, India",
      camera: "Sony DSC-WX150",
      lens: "inbuilt",
      iso: "100",
      aperture: "f/5.9",
      shutterSpeed: "1/250s",
      focalLength: "44.5mm",
      imageUrl: "https://i.ibb.co/5h2ctfC1/DSC02519-2.jpg",
      aspectRatio: "landscape",
      featured: false,
    },
    {
      id: "2",
      title: "Hilly Highway",
      description: "This beautiful landscape shows the intersection of clouds, hills and a road trip.",
      category: "Landscape",
      tags: ["mountains", "clouds", "highway", "hills", "road"],
      date: "10th January 2020",
      location: "Kullu, India",
      camera: "Sony DSC-WX150",
      lens: "inbuilt",
      iso: "100",
      aperture: "f/10.0",
      shutterSpeed: "1/400s",
      focalLength: "6.85mm",
      imageUrl: "https://i.ibb.co/ycLcX0FY/DSC02561-2.jpg",
      aspectRatio: "square",
      featured: true,
    },
    {
      id: "1",
      title: "Forest Trees",
      description: "Exploring the interplay of light and shadow in nature, this photograph captures the geometric beauty found in trees.",
      category: "Trees",
      tags: ["trees","forest", "shadows", "nature"],
      date: "4 January 2023",
      location: "Dalhousie, India",
      camera: "Sony DSC-WX150",
      lens: "inbuilt",
      iso: "160",
      aperture: "f/8.0",
      shutterSpeed: "1/125s",
      focalLength: "4.45mm",
      imageUrl: "https://i.ibb.co/6Js4JVsp/DSC03143-2.jpg",
      aspectRatio: "square",
      featured: true,
    },
  ];

  private photographerInfo: PhotographerInfo = {
    name: "Jeetesh Vasisth",
    bio: "Hi, I am Jeetesh. A 16-year-old high school senior who just can’t stop buying camera lenses. Ever since I was handed a digicam by my father to film everyone on a family trip, I have been fascinated by these machines that seemingly pause the very moment I want for an eternity. I love capturing everything from the most random location to a monkey minding his own business, because the ability to revisit what I see and share it with everyone I know has always connected to me.",
    location: "New Delhi, India",
    email: "jeeteshvasisth@gmail.com",
    specialties: ["Monkeys", "Nature", "Wildlife", "Landscapes"],
  };

  async getPhotos(): Promise<Photo[]> {
    return this.photos;
  }

  async getPhoto(id: string): Promise<Photo | undefined> {
    return this.photos.find(photo => photo.id === id);
  }

  async getPhotographerInfo(): Promise<PhotographerInfo> {
    return this.photographerInfo;
  }
}

export const storage = new MemStorage();
